#!/bin/bash
# AZAI Comprehensive Dependency Report Generator
# Creates a detailed markdown report of all dependency status

set -e

REPORT_DIR="/app/scripts/dependency_management/reports"
REPORT_FILE="$REPORT_DIR/dependency_status_$(date +%Y%m%d_%H%M%S).md"
mkdir -p "$REPORT_DIR"

echo "Generating comprehensive dependency report..."

# Create report header
cat > "$REPORT_FILE" << 'EOF'
# AZAI Dependency Status Report

**Generated:** $(date '+%Y-%m-%d %H:%M:%S %Z')

---

## 📊 Summary

EOF

# Add summary stats
cd /app/backend
PYTHON_COUNT=$(pip list --format=freeze | wc -l)
cd /app/frontend
JS_COUNT=$(cat package.json | grep -c '".*":' || echo "60+")

cat >> "$REPORT_FILE" << EOF

- **Python Packages:** $PYTHON_COUNT installed
- **JavaScript Packages:** $JS_COUNT dependencies
- **System Dependencies:** poppler-utils, MongoDB

---

## 🔒 Security Status

EOF

echo "Running security audits..."
/app/scripts/dependency_management/check_security.sh > /tmp/security_output.txt 2>&1 || true

cat >> "$REPORT_FILE" << 'EOF'

### Python Security Audit

```
EOF

grep -A 10 "Python dependencies" /tmp/security_output.txt >> "$REPORT_FILE" || echo "No vulnerabilities found" >> "$REPORT_FILE"

cat >> "$REPORT_FILE" << 'EOF'
```

### JavaScript Security Audit

```
EOF

grep -A 10 "JavaScript dependencies" /tmp/security_output.txt >> "$REPORT_FILE" || echo "No vulnerabilities found" >> "$REPORT_FILE"

cat >> "$REPORT_FILE" << 'EOF'
```

---

## 📦 Outdated Packages

EOF

echo "Checking for outdated packages..."
/app/scripts/dependency_management/check_outdated.sh > /tmp/outdated_output.txt 2>&1 || true

cat >> "$REPORT_FILE" << 'EOF'

### Python Packages

```
EOF

grep -A 20 "Python packages" /tmp/outdated_output.txt >> "$REPORT_FILE" || echo "All up to date" >> "$REPORT_FILE"

cat >> "$REPORT_FILE" << 'EOF'
```

### JavaScript Packages

```
EOF

grep -A 20 "JavaScript packages" /tmp/outdated_output.txt >> "$REPORT_FILE" || echo "All up to date" >> "$REPORT_FILE"

cat >> "$REPORT_FILE" << 'EOF'
```

---

## 🎯 Recommendations

### High Priority (Security)
- Review and apply security patches immediately
- Test thoroughly after security updates

### Medium Priority (Bug Fixes)
- Update patch versions (x.x.X) monthly
- Review changelogs before applying

### Low Priority (Features)
- Evaluate major version updates quarterly
- Test in staging environment first

---

## 📋 Update Strategy

### For Healthcare/Medicaid Application:

1. **Security First**: Apply security patches within 48 hours
2. **Stability Over Features**: Prefer stable over latest
3. **Testing Required**: Full test suite before production
4. **Version Pinning**: Maintain exact versions for predictability
5. **Staged Rollout**: Update dev → staging → production

### Next Review Date

**Recommended:** $(date -d '+1 month' '+%Y-%m-%d')

---

*Report generated by AZAI Dependency Management System*
EOF

echo "✅ Report generated: $REPORT_FILE"
echo ""
echo "View the report:"
echo "  cat $REPORT_FILE"
echo ""
echo "Or view the latest report:"
echo "  cat $REPORT_DIR/dependency_status_latest.md"

# Create symlink to latest
ln -sf "$(basename $REPORT_FILE)" "$REPORT_DIR/dependency_status_latest.md"
